"""
encryption.py
-------------
A deliberately small, dependency-free symmetric cipher for the watermark
payload. This is a hackathon prototype, not a production crypto library -
the goal is to demonstrate that the *channel* (a covert ultrasonic
watermark) can additionally carry an *encrypted* payload, so a message is
protected even if someone else detects and extracts the raw bits.

Scheme
~~~~~~
1. SHA-256(password) -> 32-byte key.
2. A keystream is generated by repeatedly hashing key || counter
   (a simple hash-based DRBG) and XORed against the plaintext bytes.
3. A CRC32 checksum of the *plaintext* is embedded by the caller so the
   decoder can tell "wrong password / corrupted signal" apart from
   "correct password".

Swap this module out for `cryptography`'s AES-GCM in a production build;
the interface (encrypt/decrypt bytes <-> bytes) would stay the same.
"""

from __future__ import annotations

import hashlib


def _keystream(key: bytes, length: int) -> bytes:
    out = bytearray()
    counter = 0
    while len(out) < length:
        block = hashlib.sha256(key + counter.to_bytes(4, "big")).digest()
        out.extend(block)
        counter += 1
    return bytes(out[:length])


def _derive_key(password: str) -> bytes:
    return hashlib.sha256(password.encode("utf-8")).digest()


def encrypt(data: bytes, password: str) -> bytes:
    if not password:
        return data
    key = _derive_key(password)
    stream = _keystream(key, len(data))
    return bytes(a ^ b for a, b in zip(data, stream))


def decrypt(data: bytes, password: str) -> bytes:
    # XOR keystream ciphers are symmetric: encrypt == decrypt.
    return encrypt(data, password)
